seed: 42
cuda_visible_devices: "0"

# Dataset & Model
dataset_name: 'jwengr/BitViper-1-20-79'
base_model_name: Qwen/Qwen3-0.6B-Base
n_tokens_per_char: 4
input_chars: ""
target_chars: ""

# Training Hyperparameters
mini_batch_size: 16
n_batch: 2
train_dataset_select: -1
val_dataset_select: 1000
test_dataset_select: 1000
epochs: 10
learning_rate: 0.0001
use_bntd: true
sliding_window: 12
neftune_alpha: 0
use_qlora: false
lora_r: 16
lora_alpha: 32


# Sequence Lengths
train_max_length: 128
valid_max_length: 128
inference_sentence_max_length: 64
inference_sentence_min_length: 32
inference_sentence_n_overlap: 3