seed: 42
cuda_visible_devices: "1"

# Dataset & Model
dataset_name: jwengr/ToxiBenchCN
base_model_name: Qwen/Qwen3-1.7B-Base
n_tokens_per_char: 4
input_chars: ""
target_chars: ""

# Training Hyperparameters
mini_batch_size: 4
n_batch: 4
epochs: 10
learning_rate: 0.0001
use_bntd: false

# Sequence Lengths
train_max_length: 128
valid_max_length: 128
inference_sentence_max_length: 64
inference_sentence_min_length: 32
inference_sentence_n_overlap: 3